spring:
 datasource:
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:models}
  username: ${DB_USER:models}
  password: ${DB_PASSWORD:models}
 jpa:
  hibernate: { ddl-auto: update }
server: { port: 8080 }
